### ISSUE TITLE
Installs wrong version of @serialport

### ISSUE THREAD

**Issue by lukecyca** [cncjs/cncjs-pi-raspbian#10]
```
  Starting CNCjs   
  [i]  Starting CNCjs   
  [!]   └ To Stop Press (CTRL + C)   
  [i]   └ ( http://192.168.2.137 ) | ( http://192.168.2.137:8000 )   
  CNCjs Start Command - - - - - - - - - - - - - - - - - -
/usr/bin/cncjs --verbose --port 8000 --config /root/.cncjs/cncrc.cfg --watch-directory /root/.cncjs/watch --host 192.168.2.137
  - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Error: Error: The module '/usr/lib/node_modules/cncjs/node_modules/@serialport/bindings/build/Release/bindings.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 83. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1144:18)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:791:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at bindings (/usr/lib/node_modules/cncjs/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/usr/lib/node_modules/cncjs/node_modules/@serialport/bindings/lib/linux.js:1:36)
    at Module._compile (internal/modules/cjs/loader.js:1085:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:791:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/usr/lib/node_modules/cncjs/node_modules/@serialport/bindings/lib/index.js:14:22)
    at Module._compile (internal/modules/cjs/loader.js:1085:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
```

**Comment by lukecyca** [comment]
I think I had remnants of other installations of node/npm/nvm from my previous attempts at installing using the official instructions (which failed). To remove them I did:

```
rm -rf /usr/lib/node_modules
rm -rf .cncjs*
rm -rf .nvm
rm -rf .npm
```

Then I re-ran this install script and it worked wonderfully. 👍
